jenkins:
  image: jenkins
  container_name: jenkins
  environment:
    - JENKINS_OPTS=--prefix=/jenkins
  expose:
    - "8080"
  volumes:
    - ~/.jenkins_home:/var/jenkins_home
nexus:
  image: sonatype/nexus:oss
  container_name: nexus
  environment:
    - CONTEXT_PATH=/nexus
  expose:
    - "8081"
###
# Probably better using data volume, but must be defined externally.
# Maybe a data volume for both jenkins and nexus?
##
#  volumes:
#    - ~/.nexus_home/sonatype-work:/sonatype-work
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  links: 
    - jenkins
    - nexus
