jenkins:
  image: jenkins
  container_name: jenkins
  expose:
    - "8080"
  volumes: 
    - ~/Development/jenkins_home:/var/jenkins_home
nginx:
  image: nginx
  ports: 
    - "80:80"
  volumes: 
    - ~/Development/jenkins/nginx.conf:/etc/nginx/nginx.conf:ro
  links: 
    - jenkins
